### ISSUE TITLE
Work on Yelp API requests

### ISSUE THREAD

**Issue by ThomBurt** [comkirk30/plant_pal#8]

**Comment by jamoore4579** [comment]
https://api.yelp.com/v3/businesses/search?location=Fort Wayne&categories=gardening

API Key: ICI4S6yJYRB24kN6bGoJ3UB8lxsWl_tPSRW_764ahFqek9pn2VhU8-W3PdAaczWjN4iCkVBuGNaPZQQaXcEh87R2k89einz0772uWa4njHkKqphljq6VWC1-mYsnYnYx
